
const BaseDatos = [
    {
        id: 1,
        titulo: "Siempre a tu lado",
        url: "https://www.dropbox.com/s/prkc07o06nvjv3m/Siempre%20a%20tu%20lado%20%282009%29.mkv",
        descripcion: "Siempre a tu lado: Basada en la historia real de un perro llamado Hachiko, que espera a su dueño fallecido en la estación de tren todos los días durante años.",
        ano: 2009,
        image:"https://i.ytimg.com/vi/MdyXi6AWcq0/hqdefault.jpg",
        genero:"Drama",

    },
    {
        id: 2,
        titulo: "Up: una aventura de alturas",
        url: "https://www.dropbox.com/s/mxuk39ydsdnz20p/Up%20%282009%29.mkv",
        descripcion: "Up: Una aventura de alturas: Un anciano viudo cumple el sueño de su difunta esposa al volar en una casa con globos, llevando consigo a un joven explorador y enfrentando aventuras inesperadas.",
        ano: 2009,
        image:"https://static.wikia.nocookie.net/el-mundo-de-pixar/images/f/f8/UP-_UNA_AVENTURA_DE_ALTURA.jpg/revision/latest?cb=20160909154734",
        genero:"Drama",
    },
    {
        id: 3,
        titulo: "Forrest Gump",
        url: "https://www.dropbox.com/s/9oin9inz0mgf5oa/Forrest%20Gump%20%281994%29%20.mkv",
        descripcion: "Forrest Gump: La vida de Forrest Gump, un hombre con discapacidades mentales, que accidentalmente se convierte en testigo y participante en eventos históricos importantes.",
        ano: 1994,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI5822dGTAnKOg4yjDQ3_LPWqlllSk2wwXkMMpwl-u09xxG4e877BYJgthrkvYYDV7Z-5Bp57tYefPJzMfnPdbvzLrwXr_tZZmBYsVtT8",
        genero:"Drama",
    },
    {
        id: 4,
        titulo: "La vida es bella",
        url: "https://www.dropbox.com/s/prkc07o06nvjv3m/Siempre%20a%20tu%20lado%20%282009%29.mkv",
        descripcion: "La vida es bella: Un padre judío en la Segunda Guerra Mundial usa su imaginación y humor para proteger a su hijo de los horrores del campo de concentración.",
        ano: 1997,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSavjA0h24wgfQDMnVuY7ir4d5Rxidnqbui5TY_EF6lZI_FKXfiKnE36tIVDTCq0ueq2Gw&usqp=CAU",
        genero:"Drama",
    },
    {
        id: 5,
        titulo: "Interestelar",
        url: "https://www.dropbox.com/s/ofryipq7euo2fud/Interstellar%20%282014%29%20.mp4",
        descripcion: "Interestelar: Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad mientras enfrentan desafíos espaciales y emocionales.",
        ano:2014,
        image:"https://pics.filmaffinity.com/Interstellar-366875261-large.jpg",
        genero:"Drama",
    },
    {
        id: 6,
        titulo: "Yo antes de ti ",
        url: "https://www.dropbox.com/s/uhl34qwlsjar8ia/yo%20antes%20de%20ti.mkv",
        descripcion: "Yo antes de ti: La historia de una joven que se convierte en cuidadora de un hombre paralizado, y cómo su relación cambia sus vidas y perspectivas.",
        ano:2016,
        image:"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRJOOdQ5JJZhxVSreJxLvs1mBVqPOORx2WjOD7FWxyuEZHaLiq5LI-_eaOei8kgGQkoB0bwXyURHq0EyQYe8Q5OnMTuhm5RyeaTP3WUgw",
        genero:"Drama",
    },
    {
        id: 7,
        titulo: "El Gladiador",
        url: "https://www.dropbox.com/s/cmfsktbbv893h15/El%20Gladiador%20%282000%29%20.mkv",
        descripcion: "Gladiador: Un general romano es traicionado y reducido a la esclavitud, buscando venganza mientras lucha como gladiador en la arena del Coliseo.",
        ano:2000,
        image:"https://pics.filmaffinity.com/Gladiator-368149580-large.jpg",
        genero:"Drama",
    },
    {
        id: 8,
        titulo: "Sin noverdad en el frente",
        url: "https://www.dropbox.com/s/yqjb8m3hykruu12/Sin%20novedad%20en%20el%20frente%20%282022%29.mkv",
        descripcion: "Sin novedad en el frente: Un drama bélico que sigue a un joven soldado alemán durante la Primera Guerra Mundial, mostrando el horror y la desilusión de la guerra.",
        ano:2022,
        image:"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSuJnlkLZV5_sT8TD1hrRpmkJCH_WPJ1xCFOLISc27Tcr7RhAix",
        genero:"Drama",
    },
    {
        id: 9,
        titulo: "Sueño de Fuga",
        url: "https://www.dropbox.com/s/9s6xg6om2irr02g/Sue%C3%B1o%20de%20Fuga%20%281994%29%20.mkv",
        descripcion: "Sueño de Fuga: Un hombre es encarcelado injustamente y lucha por su libertad mientras hace amigos en prisión y planea su escape.",
        ano:1994,
        image:"https://musicart.xboxlive.com/7/a1041200-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080",
        genero:"Drama",
    },
    {
        id: 10,
        titulo: "Oppenheimer",
        url: "https://www.dropbox.com/scl/fi/kun5wxhv022ydzs0kfyzn/Oppenheimer-2023.mkv?rlkey=f328ewp9xau5a4z1lnvatomf1&",
        descripcion: "Oppenheimer: La biografía de J. Robert Oppenheimer, el físico que lideró el desarrollo de la bomba atómica durante la Segunda Guerra Mundial y su conflicto moral posterior.",
        ano:2023,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1dPoqSYH7-PxjPf_3jZkimNJl30ENbcE7Bw&s",
        genero:"Drama",

    },
    {
        id: 11,
        titulo: "Guerra Civil",
        url: "https://www.dropbox.com/scl/fi/sxdy5rmn3x9ovb52y709m/Guerra-Civil-2024.mkv?rlkey=9e36nta2o72sy484qtd7h1j28&st=ui3hiafi&",
        descripcion: "Guerra Civil: Un conflicto épico entre dos facciones de superhéroes en el universo Marvel, que se desata por el debate sobre la regulación de los héroes.",
        ano:2014,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrDtiPr3eS8bqEkEaLxWVPaeYpCQs_QQPbRw&s",
        genero:"Drama",
    },
    {
        id: 12,
        titulo: "La idea de ti ",
        url: "https://www.dropbox.com/scl/fi/7l8serbragyfij09piz22/La-idea-de-ti-2024.mkv?rlkey=nuvohcdyk7oebnizuqx8mpwo4&st=g992735m&",
        descripcion: "La Idea de Ti: Un romance entre una madre soltera y un hombre que, al enfrentarse a desafíos personales, descubre el verdadero amor y la conexión en su vida.",
        ano:2024,
        image:"https://mx.web.img3.acsta.net/pictures/24/03/08/01/03/2426736.jpg",
        genero:"Drama",
    },
    {
        id: 13,
        titulo: "Parásitos",
        url: "https://www.dropbox.com/s/kj5iu0lx49v5vrj/Par%C3%A1sitos%20%282019%29%20.mkv",
        descripcion: "Parásitos: Una familia pobre se infiltra en la vida de una familia rica, lo que desencadena una serie de eventos inesperados y trágicos que revelan la disparidad social y económica.",
        ano:2019,
        image:"https://media.vogue.mx/photos/5e1c9b80c851470009c2fd92/2:3/w_2560%2Cc_limit/parasite-nominada-premio-oscar.jpg",
        genero:"Drama",
    },
    {
        id: 14,
        titulo: "El pianista ",
        url: "https://www.dropbox.com/s/wgpcjuzake8zjaz/El%20pianista%20%282002%29%20.mkv",
        descripcion: "El Pianista: Basada en la vida del pianista polaco judío Władysław Szpilman, muestra su lucha por sobrevivir en Varsovia durante la Segunda Guerra Mundial y el Holocausto.",
        ano:2002,
        image:"https://es.web.img2.acsta.net/pictures/14/05/27/12/07/438875.jpg",
        genero:"Drama",
    },
    {
        id: 15,
        titulo: "Diario De Una Pasion ",
        url: "https://www.dropbox.com/s/zf7h34jmyzi2iv6/Diario%20De%20Una%20Pasion%20%282004%29.mkv",
        descripcion: "Diario de una pasión: Una historia de amor entre Noah y Allie, que luchan contra las adversidades y las diferencias sociales a lo largo de los años, narrada a través de un diario leído por una anciana.",
        ano:2004,
        image:"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS_niUj3xfnAg9raOBwBsIqOSTposinK96qRgyLlNmy84PVC4b274Y81H4Mct-OJjwTHFrIaz6dYLydi--UAya5TOAw6f59agYWxKQnRA",
        genero:"Drama",
    },
    {
        id: 16,
        titulo: "El padrino",
        url: "https://www.dropbox.com/s/maxvkex1x7tplos/El%20Padrino%20%281972%29.mkv",
        descripcion: "El Padrino, sigue a la familia Corleone mientras el patriarca Vito Corleone transfiere el control del imperio criminal a su hijo Michael, quien enfrenta traiciones y conflictos para consolidar su poder.",
        ano:1972,
        image:"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQGcsFzBsTe6F6yoWYQrmnnJQJSQLNURn0QEvvWrKA5RAsuH71MQAk8VuDq4pWpc3SLHGSazZUs2IPMMJzNw1MB2KKmkcWySXk_prmQtQ",
        genero:"Drama",
    },
    {
        id: 17,
        titulo: "El Padrino Parte 2",
        url: "https://www.dropbox.com/s/1bq5frcfufbk2ou/El%20Padrino%20Parte%202%20%281974%29.mkv",
        descripcion: "El Padrino II, narra la ascensión de Vito Corleone en el pasado y la lucha de su hijo Michael por mantener el poder de la familia en el presente, enfrentando traiciones y desafíos.",
        ano:1974,
        image:"https://mx.web.img3.acsta.net/medias/nmedia/18/68/09/06/20197890.jpg",
        genero:"Drama",
    },
    {
        id: 18,
        titulo: "El Padrino Parte 3",
        url: "https://www.dropbox.com/s/cw5y8mfbngcfutt/El%20Padrino%20Parte%203%20%281990%29.mkv",
        descripcion: "El Padrino III, sigue a un envejecido Michael Corleone mientras intenta legitimar los negocios de la familia Corleone y redimirse por sus pecados pasados. Michael se enfrenta a traiciones, dificultades con la Iglesia y desafíos familiares, incluyendo la relación complicada con su sobrino Vincent y su hija Mary. En su búsqueda de redención y paz, Michael se da cuenta de que escapar de la vida del crimen es más difícil de lo que pensaba, y el costo de su poder continúa atormentándolo.",
        ano:1990,
        image:"https://es.web.img3.acsta.net/medias/nmedia/18/68/09/69/20420487.jpg",
        genero:"Drama",
    },
    {
        id: 19,
        titulo: "El padrino epílogo: la muerte de Michael Corleone",
        url: "https://www.dropbox.com/s/3gotb1vcrz3dyb9/El%20padrino%20ep%C3%ADlogo%20la%20muerte%20de%20Michael%20Corleone%20%282020%29.mkv",
        descripcion: "El Padrino Epílogo: La muerte de Michael Corleone , sigue a Michael Corleone en sus esfuerzos por legitimar los negocios de su familia y redimirse de sus pecados pasados. Mientras enfrenta desafíos internos y externos, busca proteger a su familia y asegurar su legado, todo mientras lucha con el peso de sus decisiones pasadas y las consecuencias que traen.",
        ano:2020,
        image:"https://i.blogs.es/553a3b/godfather_3_coda_critica_espinof/1366_2000.jpg",
        genero:"Drama",

    },
    {
        id: 20,
        titulo: "La La Land ",
        url: "https://dl.dropbox.com/s/bzqae5d6xsewndj/La%20La%20Land%20%282016%29.mkv",
        descripcion: "La La Land, es un musical romántico de 2016 que sigue la historia de Mia, una aspirante a actriz, y Sebastian, un pianista de jazz, mientras luchan por alcanzar sus sueños en Los Ángeles. A través de su relación, la película explora el amor, la ambición y las dificultades de perseguir las pasiones personales.",
        ano:2016,
        image:"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRTeGqgCfnw0J5becKNZ46EqVmeGOxTvjQfEl3LjlKY1AOgLcqv",
        genero:"Drama",
    }
]
module.exports = BaseDatos; // Asegúrate de que esto esté presente


// export default BaseDatos